### ISSUE TITLE
Synthetic Flow Dataset in the MPSN paper

### ISSUE THREAD

**Issue by quang-truong** [twitter-research/cwn#105]
Hi. Thank you for the well-written repo! I'm wondering if you have the synthetic flow dataset of the MPSN paper. It looks like this repo doesn't contain that dataset, only the OCEAN one.

**Comment by crisbodnar** [comment]
Hi @quang-truong,

Thanks for your question! We do provide the dataset. This script (https://github.com/twitter-research/cwn/blob/main/exp/scripts/mpsn-flow.sh) runs the experiments for the synthetic dataset. The code for the dataset can also be found in this file: https://github.com/twitter-research/cwn/blob/main/data/datasets/flow.py. 

I will close this issue now, but feel free to reopen it if you have further questions or comments.
