### ISSUE TITLE
issue in running the code

### ISSUE THREAD

**Issue by JeffreyHuSC** [twitter-research/cwn#92]
Traceback (most recent call last):
  File "/Users/sirihu/.conda/envs/envcwn/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/sirihu/.conda/envs/envcwn/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/sirihu/data/cwn/exp/run_mol_exp.py", line 105, in <module>
    exp_main(passed_args)
  File "/Users/sirihu/data/cwn/exp/run_mol_exp.py", line 26, in exp_main
    curves = main(parsed_args)
  File "/Users/sirihu/data/cwn/exp/run_exp.py", line 90, in main
    train_loader = DataLoader(dataset.get_split('train'), batch_size=args.batch_size,
  File "/Users/sirihu/data/cwn/data/datasets/dataset.py", line 370, in get_split
    if self.__indices__ is not None:
AttributeError: 'OGBDataset' object has no attribute '__indices__'

   def get_split(self, split):
        if split not in ['train', 'valid', 'test']:
            raise ValueError(f'Unknown split {split}.')
        idx = self.get_idx_split()[split]
        if idx is None:
            raise AssertionError("No split information found.")
370:        if self.__indices__ is not None:
            raise AssertionError("Cannot get the split for a subset of the original dataset.")
        return self[idx]

**Comment by crisbodnar** [comment]
Can you please provide the exact command you used and all the context for us to be able to debug? Are you using the version of the libraries specified in our requirements file? Did you make any modifications to the code? 

Based on the error, it seems you are trying to further split one of the train, test or validation splits.

**Comment by crisbodnar** [comment]
Hi @JeffreyHuSC! We have spotted a problem with the dependencies when using CUDA-based libraries. This has been solved in this PR: https://github.com/twitter-research/cwn/pull/94. This might have caused the issues you observed. Please try running the code again by following the latest installation instructions from the README. 

I will be closing this issue now, but feel free to reopen it if this problem shows up again.
