### ISSUE TITLE
# of Parameters on ZINC-500k

### ISSUE THREAD

**Issue by b05901024** [twitter-research/cwn#97]
Hi,

I'm currently researching on graph representation, and want to compare the performance between SOTAs. I'm curious about the performance and the number of parameters for CIN on ZINC-500k. I just want to check whether #  of parameters for MAE=0.079 (CIN) is about 1.7M and MAE=0.094 (CIN-small) is about 130k. BTW, I want to know whether you have conducted experiment that # of parameters approximately equal to 500k. Thanks

**Comment by crisbodnar** [comment]
We did not. We became aware of the convention of upper bounding the number of parameters of ZINC to 500k only later, unfortunately. But the existent code should make it easy to run such an experiment by simply adjusting the number of layers or feature channels. Let us know if you encounter any problems with that.

**Comment by b05901024** [comment]
OK, very thanks for your reply.
