### ISSUE TITLE
Working on QM9 dataset

### ISSUE THREAD

**Issue by AdarshMJ** [twitter-research/cwn#98]
Hi! So I have modified relevant parts of the datasets/zinc.py to work on QM9 dataset. 

The initial conversion to cell complexes is working however while training I get an assertion error -
![Screenshot 2022-04-01 at 11 30 38](https://user-images.githubusercontent.com/24205200/161236731-6f564738-a1c4-4528-a003-dabde121abd7.png)

Any idea how to resolve this?

Thanks in advance!

**Comment by crisbodnar** [comment]
Hi! The model you are using is made specifically for ZINC. There we assert that the edge features are one-dimensional vectors (i.e. the bond type). It seems that is not the case for the dataset you are using (i.e. QM9).
